version: '3'

services:
  db:
    image: mariadb:latest
    restart: always
    volumes:
      - db:/var/lib/mysql
    env-file:
      - envfile
  app:
    image: nextcloud:latest
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
    restart: always
