version: '3'

services:
  db:
    image: mariadb:latest
    volumes:
      - ${DB_MOUNTPOINT}:/var/lib/mysql
    env_file:
      - envfile
    environment:
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_INITDB_SKIP_TZINFO: 1
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--innodb_strict_mode=OFF"
      - "--innodb_read_only_compressed=OFF"
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  app:
    image: nextcloud:custom
    ports:
      - ${PORT}:80
    volumes:
      - ${APPDATA_MOUNTPOINT}:/var/www/html
      - ${MNT1}:${MNT1}
      - ${MNT2}:${MNT2}
      - ${MNT3}:${MNT3}
    env_file:
      - envfile
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
