version: '3'

services:
  db:
    image: mariadb:latest
    volumes:
      - ${DB_MOUNTPOINT}:/var/lib/mysql
    env_file:
      - envfile
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--innodb_strict_mode=OFF"
      - "--innodb_read_only_compressed=OFF"
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  app:
    image: nextcloud:custom
    ports:
      - ${PORT}:80
    volumes:
      - ${APPDATA_MOUNTPOINT}:/var/www/html
      - ${MNT1}:/mnt/main
      - ${MNT2}:/mnt/sub
      - ${MNT3}:/mnt/archive
    env_file:
      - envfile
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
